/**
 * Demo Data — rich, realistic seed data for Samiha Chowdhury's job search.
 * These opportunities have been pre-scored using the real scoring engine
 * to demonstrate the hierarchy and scoring logic truthfully.
 */

const now = new Date();
const daysAgo = (n) => new Date(now - n * 864e5).toISOString();

export const DEMO_OPPORTUNITIES = [
  // ── TPM ──────────────────────────────────────────────────────────────────
  {
    id: 'demo-1',
    title: 'Senior Technical Project Manager',
    company: 'ANZ Banking Group',
    location: 'Melbourne, VIC (Hybrid)',
    url: 'https://example.com/job/1',
    description:
      'Lead technical delivery of digital banking platform projects. Manage SDLC from requirements through deployment. Stakeholder management across engineering, product, and operations. Agile/scrum delivery cadence. PMP preferred. Jira, Confluence.',
    source: 'src-demo',
    dedup_hash: 'demo0001',
    is_duplicate: false,
    lane: 'tpm',
    fit_score: 94,
    fit_signals: ['title: TPM exact/partial match', 'title: TPM exact/partial match', 'tool/method: agile', 'tool/method: scrum', 'tool/method: jira', 'tool/method: confluence', 'tool/method: pmp', 'seniority: senior/lead/principal signal found'],
    recommended: true,
    high_fit: true,
    resume_emphasis: 'tpm',
    recommendation_text: 'Strong TPM fit — lead with technical delivery, stakeholder management, and SDLC ownership.',
    status: 'queued',
    approval_state: 'pending',
    ingested_at: daysAgo(1),
    last_action_date: daysAgo(1),
    human_override: null,
    notes: '',
    stale_flag: false,
  },
  {
    id: 'demo-2',
    title: 'Technical Project Manager — Cloud Migration',
    company: 'Telstra',
    location: 'Sydney, NSW (Remote-Friendly)',
    url: 'https://example.com/job/2',
    description:
      'Drive cloud migration programme across 12 business units. Own technical roadmap, risk management, and executive stakeholder reporting. AWS or Azure experience valuable. Agile delivery in complex enterprise environment.',
    source: 'src-demo',
    dedup_hash: 'demo0002',
    is_duplicate: false,
    lane: 'tpm',
    fit_score: 91,
    fit_signals: ['title: TPM exact/partial match', 'desc keywords: technical roadmap, risk management', 'tool/method: agile', 'seniority: senior/lead/principal signal found'],
    recommended: true,
    high_fit: true,
    resume_emphasis: 'tpm',
    recommendation_text: 'Strong TPM fit — lead with technical delivery, stakeholder management, and SDLC ownership.',
    status: 'approved',
    approval_state: 'approved',
    ingested_at: daysAgo(5),
    applied_date: null,
    last_action_date: daysAgo(3),
    human_override: {
      action: 'approve',
      reason: 'Excellent cloud migration scope, strong seniority match.',
      decided_at: daysAgo(3),
      original_recommendation: true,
      original_fit_score: 91,
    },
    notes: 'Draft cover letter started.',
    stale_flag: false,
  },
  {
    id: 'demo-3',
    title: 'IT Project Manager — Digital Transformation',
    company: 'Woolworths Group',
    location: 'Bella Vista, NSW',
    url: 'https://example.com/job/3',
    description:
      'Manage delivery of digital transformation projects across retail technology platforms. Cross-functional team coordination, agile methodology, stakeholder engagement.',
    source: 'src-demo',
    dedup_hash: 'demo0003',
    is_duplicate: false,
    lane: 'tpm',
    fit_score: 82,
    fit_signals: ['title: TPM exact/partial match', 'desc-match: digital transformation, agile', 'tool/method: agile'],
    recommended: true,
    high_fit: false,
    resume_emphasis: 'tpm',
    recommendation_text: 'Strong TPM fit — lead with technical delivery, stakeholder management, and SDLC ownership.',
    status: 'applied',
    approval_state: 'approved',
    ingested_at: daysAgo(18),
    applied_date: daysAgo(14),
    last_action_date: daysAgo(14),
    human_override: { action: 'approve', reason: '', decided_at: daysAgo(16), original_recommendation: true, original_fit_score: 82 },
    notes: 'Applied via company portal.',
    stale_flag: false,
    next_action: 'Follow up if no response',
    next_action_due: daysAgo(-7),
  },
  // ── Delivery Manager ──────────────────────────────────────────────────────
  {
    id: 'demo-4',
    title: 'Delivery Manager — Enterprise Agile',
    company: 'Commonwealth Bank',
    location: 'Sydney CBD, NSW (Hybrid)',
    url: 'https://example.com/job/4',
    description:
      'Lead agile delivery across multiple squads. Sprint planning, retrospectives, release management. Scaled Agile framework (SAFe). Stakeholder reporting and impediment removal.',
    source: 'src-demo',
    dedup_hash: 'demo0004',
    is_duplicate: false,
    lane: 'delivery_manager',
    fit_score: 88,
    fit_signals: ['title: Delivery Manager match', 'tool/method: agile', 'tool/method: safe agile', 'tool/method: scaled agile', 'seniority: senior/lead/principal signal found'],
    recommended: true,
    high_fit: true,
    resume_emphasis: 'delivery',
    recommendation_text: 'Strong Delivery Manager fit — emphasise agile delivery cadence and team outcomes.',
    status: 'queued',
    approval_state: 'pending',
    ingested_at: daysAgo(2),
    last_action_date: daysAgo(2),
    human_override: null,
    notes: '',
    stale_flag: false,
  },
  {
    id: 'demo-5',
    title: 'Agile Delivery Lead',
    company: 'Atlassian',
    location: 'Sydney, NSW (Remote OK)',
    url: 'https://example.com/job/5',
    description:
      'Drive agile delivery cadence for two product squads. Jira workflow optimisation, sprint health metrics, velocity tracking. Confluence documentation standards.',
    source: 'src-demo',
    dedup_hash: 'demo0005',
    is_duplicate: false,
    lane: 'delivery_manager',
    fit_score: 85,
    fit_signals: ['title: Delivery Manager match', 'tool/method: agile', 'tool/method: jira', 'tool/method: confluence', 'seniority: senior/lead/principal signal found'],
    recommended: true,
    high_fit: true,
    resume_emphasis: 'delivery',
    recommendation_text: 'Strong Delivery Manager fit — emphasise agile delivery cadence and team outcomes.',
    status: 'interviewing',
    approval_state: 'approved',
    ingested_at: daysAgo(25),
    applied_date: daysAgo(20),
    last_action_date: daysAgo(5),
    human_override: { action: 'approve', reason: 'Excellent Atlassian culture fit.', decided_at: daysAgo(22), original_recommendation: true, original_fit_score: 85 },
    notes: 'Second round interview scheduled.',
    stale_flag: false,
  },
  // ── Operations Manager (Conditional — qualified) ──────────────────────────
  {
    id: 'demo-6',
    title: 'Technical Operations Manager',
    company: 'Services Australia',
    location: 'Canberra / Remote ACT',
    url: 'https://example.com/job/6',
    description:
      'Lead technical operational readiness and compliance for digital government services. ITSM framework, service management, IT operations governance. APS6 equivalent.',
    source: 'src-demo',
    dedup_hash: 'demo0006',
    is_duplicate: false,
    lane: 'ops_manager',
    fit_score: 72,
    fit_signals: ['title: Ops Manager qualified match', 'tool/method: readiness, compliance, itsm', 'seniority: senior/lead/principal signal found'],
    recommended: true,
    high_fit: false,
    resume_emphasis: 'ops',
    recommendation_text: 'Qualified Ops fit — emphasise readiness, compliance, and technical operations track record.',
    status: 'discovered',
    approval_state: 'pending',
    ingested_at: daysAgo(0.5),
    last_action_date: daysAgo(0.5),
    human_override: null,
    notes: '',
    stale_flag: false,
  },
  // ── Operations Manager (Generic — downgraded) ────────────────────────────
  {
    id: 'demo-7',
    title: 'Operations Manager',
    company: 'Retail Co Pty Ltd',
    location: 'Melbourne, VIC',
    url: 'https://example.com/job/7',
    description:
      'Manage daily retail operations, staff rostering, and supplier relationships. KPI tracking, budget management, team leadership.',
    source: 'src-csv',
    dedup_hash: 'demo0007',
    is_duplicate: false,
    lane: 'generic_pm',
    fit_score: 28,
    fit_signals: ['operations manager — no technical qualifier detected', 'tool/method: budget management'],
    recommended: false,
    high_fit: false,
    resume_emphasis: 'tpm',
    recommendation_text: 'Not recommended — low fit, consider skipping.',
    status: 'rejected',
    approval_state: 'rejected',
    ingested_at: daysAgo(7),
    last_action_date: daysAgo(6),
    human_override: { action: 'reject', reason: 'Generic ops role — no technical scope.', decided_at: daysAgo(6), original_recommendation: false, original_fit_score: 28 },
    notes: '',
    stale_flag: false,
  },
  // ── Program Manager (Selective — qualified) ───────────────────────────────
  {
    id: 'demo-8',
    title: 'Senior Programme Manager — Digital Transformation',
    company: 'KPMG Australia',
    location: 'Sydney, NSW',
    url: 'https://example.com/job/8',
    description:
      'Lead governance framework for multi-year enterprise digital transformation programme. PMO establishment, portfolio management, board-level reporting, stakeholder governance.',
    source: 'src-demo',
    dedup_hash: 'demo0008',
    is_duplicate: false,
    lane: 'program_manager',
    fit_score: 76,
    fit_signals: ['title: Program Manager qualified match', 'qualifier: governance, pmo, portfolio, enterprise', 'seniority: senior/lead/principal signal found'],
    recommended: true,
    high_fit: false,
    resume_emphasis: 'program',
    recommendation_text: 'Qualified PgM fit — emphasise governance, PMO, and portfolio-level delivery.',
    status: 'queued',
    approval_state: 'pending',
    ingested_at: daysAgo(1),
    last_action_date: daysAgo(1),
    human_override: null,
    notes: '',
    stale_flag: false,
  },
  // ── Stale Example ─────────────────────────────────────────────────────────
  {
    id: 'demo-9',
    title: 'Technical Project Manager — FinTech Platform',
    company: 'Zip Co',
    location: 'Sydney, NSW',
    url: 'https://example.com/job/9',
    description:
      'Drive technical project delivery for BNPL platform. Agile delivery, stakeholder management, risk management, Jira, cross-functional team.',
    source: 'src-demo',
    dedup_hash: 'demo0009',
    is_duplicate: false,
    lane: 'tpm',
    fit_score: 86,
    fit_signals: ['title: TPM exact/partial match', 'tool/method: agile', 'tool/method: jira', 'tool/method: risk management'],
    recommended: true,
    high_fit: true,
    resume_emphasis: 'tpm',
    recommendation_text: 'Strong TPM fit.',
    status: 'applied',
    approval_state: 'approved',
    ingested_at: daysAgo(50),
    applied_date: daysAgo(45),
    last_action_date: daysAgo(45),
    human_override: { action: 'approve', reason: '', decided_at: daysAgo(47), original_recommendation: true, original_fit_score: 86 },
    notes: 'No response yet.',
    stale_flag: true,
    stale_reason: 'No response in 45 days — likely ghosted.',
    suggested_next_status: 'ghosted',
  },
];

export const DEMO_LOGS = [
  {
    id: 'log-1',
    source_id: 'src-demo',
    run_at: daysAgo(0.5),
    count_discovered: 7,
    count_deduped: 0,
    count_new: 7,
    errors: [],
    status: 'success',
  },
  {
    id: 'log-2',
    source_id: 'src-csv',
    run_at: daysAgo(7),
    count_discovered: 3,
    count_deduped: 1,
    count_new: 2,
    errors: [],
    status: 'success',
  },
  {
    id: 'log-3',
    source_id: 'src-rss-seek',
    run_at: daysAgo(1),
    count_discovered: 0,
    count_deduped: 0,
    count_new: 0,
    errors: ['BLOCKED: live intake is disabled (LIVE_INTAKE_ENABLED != true)'],
    status: 'failure',
  },
  {
    id: 'log-4',
    source_id: 'stale-scan',
    run_at: daysAgo(1),
    count_discovered: 9,
    count_deduped: 0,
    count_new: 1,
    errors: [],
    status: 'success',
  },
];
